### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by davidgasquez** [bufferapp/README#6]
Heya @KatieLo! I was looking forward adding out Code of Conduct. Right now we also have it in [another repository](https://github.com/bufferapp/code-of-conduct). Curious if we want to duplicate it, keep it there or move it under this repository.

Happy to take care of anything, just want to get your thoughts!

**Comment by KatieLo** [comment]
hey @davidgasquez! I will duplicate it, because that Repo now has lots of links to it on the internet from twitter, blogs etc and we want those to stay working. Great point!
